apply plugin: 'com.android.library'

apply from: "${rootDir}/gradle/android_general.gradle"

android {
    namespace 'com.anysoftkeyboard.jnidictionaryv2'
}

dependencies {
    implementation project(':ime:dictionaries')
    implementation project(':ime:base')
    implementation libs.androidx.annotation
}
